{{- if .Values.gateway.enabled -}}
{{- $fullName := include "nodejs-helm-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $defaultHostname := "unset-hostname" -}}
{{- if gt (len .Values.gateway.routes) 0 -}}
{{- $defaultHostname = (index .Values.gateway.routes 0).hostname -}}
{{- end -}}

# ============================================================
# 主要路由: {{ $defaultHostname }}
# ============================================================
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nodejs-helm-template.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.gatewayName }}
      namespace: {{ .Values.gateway.gatewayNamespace }}
  hostnames:
    {{- range .Values.gateway.routes }}
    {{- if not .redirect }}
    - {{ .hostname | quote }}
    {{- end }}
    {{- end }}
  rules:
    {{- range .Values.gateway.rules }}
    - matches:
        - path:
            type: {{ .pathType | default "PathPrefix" }}
            value: {{ .path }}
      {{- if .redirect }}
      filters:
        - type: RequestRedirect
          requestRedirect:
            {{- if .redirect.scheme }}
            scheme: {{ .redirect.scheme }}
            {{- end }}
            {{- if .redirect.hostname }}
            hostname: {{ .redirect.hostname }}
            {{- end }}
            {{- if .redirect.path }}
            path:
              type: ReplaceFullPath
              replaceFullPath: {{ .redirect.path }}
            {{- end }}
            statusCode: {{ .redirect.statusCode | default 301 }}
      {{- else }}
      backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
      {{- end }}
    {{- end }}

    # 預設路由
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}

{{- if .Values.gateway.redirectRoutes }}
---
# ============================================================
# 重定向路由 (例: 舊網域 → 新網域)
# ============================================================
{{- range .Values.gateway.redirectRoutes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-redirect-{{ .hostname | replace "." "-" }}
  labels:
    {{- include "nodejs-helm-template.labels" $ | nindent 4 }}
spec:
  parentRefs:
    - name: {{ $.Values.gateway.gatewayName }}
      namespace: {{ $.Values.gateway.gatewayNamespace }}
  hostnames:
    - {{ .hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            hostname: {{ .targetHostname }}
            statusCode: {{ .statusCode | default 301 }}
{{- end }}
{{- end }}

{{- end }}
